site_name: Jiaji Deng
site_url: https://dengjiaji.github.io/self/
site_description: "dengjiaji's blog"
repo_url: https://github.com/Dengjiaji
repo_name: self

theme:
  name: shadcn
  image: figure/icon.jpg
  show_stargazers: true
  locale: en
  show_datetime: true

plugins:
  - search
  - excalidraw

nav:
  - Home: index.md
  - blogs:
      - Proactive Agents: blog/2025-11-19.md
      - 智力服务与智能生命: blog/2026-01-16-无生命的智能-1.md
      - 当智能成为基础设施: blog/2026-01-30-无生命的智能-2.md
      - 消失的未来: blog/2026-03-23-无生命的智能-3.md

markdown_extensions:
  admonition:
  codehilite:
  fenced_code:
  footnotes:
  extra:
  pymdownx.blocks.details:
  pymdownx.tabbed:
  pymdownx.blocks.tab:
    combine_header_slug: true
    separator: ___
  pymdownx.progressbar:
  pymdownx.snippets:
  pymdownx.arithmatex:
    generic: true
  shadcn.extensions.echarts.alpha:
  shadcn.extensions.codexec:
  shadcn.extensions.iconify:

# pip install mkdocs-shadcn
# mkdocs build
# mkdocs serve
# mkdocs gh-deploy --force
